[package]
authors = ["Pascal Hartig <phartig@rdrei.net>"]
name = "revmenu"
version = "0.1.0"
[dependencies]
clap = "2.29.4"
console = "0.6.1"
exitcode = "1.1.2"
failure = "0.1.1"
nom = "4.0.0-beta1"
itertools = "0.7.7"
colored = "1.6.0"
